import { Components } from '../../shared/types';

export const components: Components[] = [
  {
    id: '123',
    image: '',
    name: 'MainBlock',
    displayName: 'Main block',
    fields: {
      title: {
        type: 'string',
        fieldName: 'title',
        value: '',
        typeField: 'short-text',
        required: true,
        placeholder: 'Put title',
      },
      description: {
        type: 'string',
        fieldName: 'description',
        value: '',
        typeField: 'long-text',
        required: true,
        placeholder: 'Put description',
      },
      image: {
        type: 'string',
        fieldName: 'image',
        value: '',
        typeField: 'image',
        required: true,
        placeholder: 'Put image',
      },
    },
  },
  {
    id: 'heading2313213',
    image: '',
    name: 'Heading',
    displayName: 'Заголовок',
    fields: {
      title: {
        type: 'string',
        fieldName: 'title',
        value: '',
        typeField: 'short-text',
        required: true,
        placeholder: 'Put title',
      },
      description: {
        type: 'string',
        fieldName: 'description',
        value: '',
        typeField: 'long-text',
        required: false,
        placeholder: 'Put description',
      },
      image: {
        type: 'string',
        fieldName: 'image',
        value: '',
        typeField: 'image',
        required: false,
        placeholder: 'Put image',
      },
      url: {
        type: 'string',
        fieldName: 'url',
        value: '',
        typeField: 'short-text',
        required: false,
        placeholder: 'Put url',
      },
    },
  },
  {
    id: 'tariff2313213',
    image: '',
    name: 'Tariff',
    displayName: 'Тарифы',
    fields: {
      mainTitle: {
        type: 'string',
        fieldName: 'mainTitle',
        value: '',
        typeField: 'short-text',
        required: true,
        placeholder: 'Put title',
      },
      description: {
        type: 'string',
        fieldName: 'description',
        value: '',
        typeField: 'long-text',
        required: true,
        placeholder: 'Put description',
      },
      url: {
        type: 'string',
        fieldName: 'url',
        value: '',
        typeField: 'short-text',
        required: false,
        placeholder: 'Put url',
      },
    },
  },
  {
    id: '1233',
    image: '',
    name: 'MainBlockTest',
    displayName: 'Test Main block',
    fields: {
      title_test: {
        type: 'string',
        fieldName: 'title_test',
        value: '',
        typeField: 'short-text',
        required: true,
        placeholder: 'Put test title',
      },
      text_test: {
        type: 'string',
        fieldName: 'text_test',
        value: '',
        typeField: 'long-text',
        required: true,
        placeholder: 'Put test text',
      },
      description_test: {
        type: 'string',
        fieldName: 'description_test',
        value: '',
        typeField: 'long-text',
        required: true,
        placeholder: 'Put test description',
      },
    },
  },
];
