const MediaCardStyle = {
  card: {
    display: 'flex',
    justifyContent: 'center',
    boxSizing: 'border-box',
    flexBasis: '420px',
    minWidth: '272px',
    maxHeight: '262px',
    borderRadius: '30px',
    overflow: 'hidden',
    cursor: 'pointer',
    position: 'relative',
  },
  image: {
    width: '100%',
    height: '100%',
  },
  noImageWrapper: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ccc',
  },
  iconPlayWrapper: {
    position: 'absolute',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '60px',
    height: '60px',
    borderRadius: '50%',
    background: '#fff',
    zIndex: 10,
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
  modal: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '80%',
    maxWidth: '800px',
    backgroundColor: '#fff',
    border: 'none',
    boxShadow: 24,
    padding: '16px',
    outline: 0,
    overflow: 'hidden',
    '@media (max-width:600px)': {
      width: '90%',
      padding: '16px',
    },
    '@media (min-width:600px) and (max-width:960px)': {
      width: '70%',
      padding: '24px',
    },
  },
  closeButton: {
    position: 'absolute',
    top: '10px',
    right: '10px',
    zIndex: 1300, // Убедитесь, что кнопка выше модального окна
  },
};

export default MediaCardStyle;
